version: '3'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    container_name: my-backend-container
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: my-mongodb-container
    volumes:
      - my-mongodb-data:/data/db

volumes:
  my-mongodb-data: