version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    container_name: my-backend-container 

    # docker run -d -p 3010:3000 --name backend-container-10 backend:v3
